import { Category, Status } from 'types'

export const defaultActivities = [
  {
    id: 'video chat with a friend or family',
    label: 'video chat with a friend or family',
    category: Category.Social,
    status: Status.Pending,
  },
  {
    id: 'cook a healthy meal',
    label: 'cook a healthy meal',
    category: Category.Physical,
    status: Status.Pending,
  },
  {
    id: 'write down something you’re grateful for',
    label: 'write down something you’re grateful for',
    category: Category.Spiritual,
    status: Status.Pending,
  },
  {
    id: 'read a book',
    label: 'read a book',
    category: Category.Intellectual,
    status: Status.Pending,
  },
  {
    id: 'do shopping for groceries',
    label: 'do shopping for groceries',
    category: Category.Chores,
    status: Status.Pending,
  },
  {
    id: 'draw a picture of a puppy',
    label: 'draw a picture of a puppy',
    category: Category.Fun,
    status: Status.Pending,
  },
  {
    id: 'call one of your friends or family',
    label: 'call one of your friends or family',
    category: Category.Social,
    status: Status.Pending,
  },
  {
    id: 'send a selfie to a friend or family',
    label: 'send a selfie to a friend or family',
    category: Category.Social,
    status: Status.Pending,
  },
  {
    id: 'send a card or small gift to a loved one',
    label: 'send a card or small gift to a loved one',
    category: Category.Social,
    status: Status.Pending,
  },
  {
    id: 'practice yoga',
    label: 'practice yoga',
    category: Category.Physical,
    status: Status.Pending,
  },
  {
    id: 'follow a workout video',
    label: 'follow a workout video',
    category: Category.Physical,
    status: Status.Pending,
  },
  {
    id: 'listen to a new piece of music',
    label: 'listen to a new piece of music',
    category: Category.Spiritual,
    status: Status.Pending,
  },
  {
    id: 'listen to your favourite song',
    label: 'listen to your favourite song',
    category: Category.Spiritual,
    status: Status.Pending,
  },
  {
    id: 'spend half an hour learning something new',
    label: 'spend half an hour learning something new',
    category: Category.Intellectual,
    status: Status.Pending,
  },
  {
    id: 'do a puzzle',
    label: 'do a puzzle',
    category: Category.Intellectual,
    status: Status.Pending,
  },
  {
    id: 'listen to your favourite song',
    label: 'listen to your favourite song',
    category: Category.Intellectual,
    status: Status.Pending,
  },
  {
    id: 'clean your space',
    label: 'clean your space',
    category: Category.Chores,
    status: Status.Pending,
  },
  {
    id: 'do some laundry',
    label: 'do some laundry',
    category: Category.Chores,
    status: Status.Pending,
  },
  {
    id: 'watch a movie',
    label: 'watch a movie',
    category: Category.Fun,
    status: Status.Pending,
  },
  {
    id: 'play a game',
    label: 'play a game',
    category: Category.Fun,
    status: Status.Pending,
  },
  {
    id: 'take a photo',
    label: 'take a photo',
    category: Category.Fun,
    status: Status.Pending,
  },
]
